### PR TITLE
Minor change

### PR DESCRIPTION
**Pull request by oleersoy**
It seems to be adding old pull request material to each request.  This is the last PR for this tutorial I think.  Very minor change on the summary.

### CODE REVIEW

**Comment by dsyer** [comment]
If you want to make a small change, please rebase to the remote master and re-push to your fork.

**Comment by oleersoy** [comment]
Sorry I don't understand what that means ... the change is like 3 words (I think the grammer is wrong - and that's the only thing left in this specific tutorial I think).  This is the link to the change:
https://github.com/spring-guides/tut-spring-security-and-angular-js/pull/112/commits/a6bc642864de93ca1debfe197df3ce30470d9540

Anyways like I said it's very minor so if you are OK with it we can close it.

**Comment by oleersoy** [comment]
Oh wait - if I delete this fork, then refork, the old changes will go away.  That way if I see anything in the future tutorials other tutorials and submit a PR, the this PR will be cleaner.  Is that what you want me to do?

**Comment by dsyer** [comment]
No, don't delete your fork (you might have something in it you want to keep). I'll fix it.

**Comment by dsyer** [comment]
Fixed in ffb5bd6

**Comment by oleersoy** [comment]
Cool :+1:

**Pull request closed without merging**
