### PR TITLE
Navigate to home page when authenticated user clicks login

### PR DESCRIPTION
**Pull request by duongvu89**
May I add a minor fix for enter() function(added code is in bold):
enter = function() {
                if ($location.path() != auth.loginPath) {
                    auth.path = $location.path();
                    if (!auth.authenticated) {
                        $location.path(auth.loginPath);
                    _**} else {
                    if (auth.authenticated) {
                        $location.path(auth.homePath);
                    }
                }**_
            }

### CODE REVIEW

**Comment by duongvu89** [comment]
Anyone has write access please help me merge the conflicts...
And I only want make a pull request for my last commit [https://github.com/duongvu89/spring-security-angular/commit/dcaa6a3a1a1bc1ade5d4d2492c8b85afc00af524](url)

**Comment by dsyer** [comment]
Thanks for the suggestion. I'm not sure why the change is necessary, though, and it might break something (the "return to current path" after login feature provided by spring security). Can you elaborate a bit?

The conflicts are your responsibility as the author of the pull request. It's probably best to start again if it's a really small change. In any case rebase your local branch to master in this repo before you update the pr.

**Comment by duongvu89** [comment]
Hi Mr. Syer,

Thanks for your reply. This is a minor change and will be useful in case some users don't like to be able to access the login page when they already logged in. And I have already tested again and I am happy to let you know it will not break the "return to current path", in case you type in login path, after successfully log in, Spring Security will redirect to login path and this block of code will run and back to home page.

**Comment by dsyer** [comment]
Conflicts still present. I guess this isn't an important change (closing).

**Comment by duongvu89** [comment]
Angular team is working hard on routing for Angular 2 so I guess we don't need to deep dive in these problems any more. :)

**Pull request closed without merging**
