### PR TITLE
Replace mentions of "Angular JS" with "Angular"

### PR DESCRIPTION
**Pull request by thetric**
This is an Obvious Fix replacing "AngularJS" with "Angular", following [Angular's Branding Guidelines](https://blog.angularjs.org/2017/01/branding-guidelines-for-angular-and.html):

> AngularJS for any 1.x release, and Angular for any 2+ release.

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@thetric Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-guides/tut-spring-security-and-angular-js&pullRequestId=176)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-guides/tut-spring-security-and-angular-js&pullRequestId=176) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@thetric This Pull Request contains an obvious fix. Signing the Contributor License Agreement is not necessary.

**Comment by thetric** [comment]
Updated the PR to only change the text occurrences, not the links

**Comment by thetric** [comment]
@dsyer I applied your change request. Can you please review my changes?

**Pull request merged**
