### PR TITLE
sentence structure

### PR DESCRIPTION
**Pull request by oleersoy**

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@oleersoy Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-guides/tut-spring-security-and-angular-js&pullRequestId=110)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-guides/tut-spring-security-and-angular-js&pullRequestId=110) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/faq) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@oleersoy Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-guides/tut-spring-security-and-angular-js&pullRequestId=110)!

**Comment by dsyer** [comment]
Thanks. I'll fix the typo with "be". But "behaviour" is actually spelled correctly, so no need to change that.

**Comment by dsyer** [comment]
Fixed via ec6e936 thanks.

**Comment by oleersoy** [comment]
Cool - Thanks for writing these brilliant tutorials.  They are a huge help!

**Pull request closed without merging**
