### PR TITLE
Update single readme

### PR DESCRIPTION
**Pull request by blairnangle**
Update the single README to bring the guide in line with the (correct) source code.

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@blairnangle Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-guides/tut-spring-security-and-angular-js&pullRequestId=151)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-guides/tut-spring-security-and-angular-js&pullRequestId=151) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@blairnangle Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-guides/tut-spring-security-and-angular-js&pullRequestId=151)!

**Comment by dsyer** [comment]
I think that difference was intentional. IIRC there's a comment somewhere in threat to say that there are a couple of extra features in the source code sample compared to the snippets. It keeps it simple, without actually breaking anything.

**Comment by blairnangle** [comment]
I followed the guide in the README and the Angular component of my application wasn't working correctly. After consulting the source code, I was able to fix it.

**Comment by dsyer** [comment]
So maybe to could narrow down the difference. I don't think you need to inject `$route` for example, for the app to work.

**Comment by dsyer** [comment]
Closed for lack of interest

**Pull request closed without merging**
