### PR TITLE
use equals-sign in properties files

### PR DESCRIPTION
**Pull request by otrosien**
... (hopefully) using proper upstream repository now.

### CODE REVIEW

**Comment by dsyer** [comment]
Why?

**Comment by otrosien** [comment]
Consistency. And honestly, I didn't even know you could use colon in properties files in general, it looked like a left-over from trying to convert yaml to properties to me.

**Comment by dsyer** [comment]
I'm all for consistency, but I like the colons. Are there some files with equals already?

**Comment by otrosien** [comment]
some files have both mixed, e.g. oauth2-vanilla/authserver/src/main/resources/application.properties - so it's just a matter of deciding which way to go.

**Comment by dsyer** [comment]
Fixed in 18209c5

**Pull request closed without merging**
