### PR TITLE
spelling

### PR DESCRIPTION
**Pull request by oleersoy**

### CODE REVIEW

**Comment by dsyer** [comment]
Thanks. Most of those changes were redundant or unnecessary, but the one that I didn't catch yet I have applied independently (ae9abe2). Please rebase onto master next time you send a PR - that way there is more chance it will not be duplicating effort.

**Comment by oleersoy** [comment]
Sounds good - Thanks for the heads up.

**Comment by oleersoy** [comment]
I'm trying to understand how to go about rebasing my fork.  Upon following some of the [SO](http://stackoverflow.com/questions/7244321/how-do-i-update-a-github-forked-repository) instructions, it lead me to review my PRs.  It looks like some of them may not have been applied even though they are correct ... I might be looking at it wrong since this part of the process is new to me. 

For example one PR references the word 

> [codes](https://github.com/spring-guides/tut-spring-security-and-angular-js/pull/125/commits/a6bc642864de93ca1debfe197df3ce30470d9540)
> vs
> code

It really should be code based on this [Is it wrong to use the word codes in a programming context](http://english.stackexchange.com/questions/20455/is-it-wrong-to-use-the-word-codes-in-a-programming-context)

So was this fixed?  The reason I'm wondering is that it still shows up when I try to go through the rebasing process ...

**Comment by dsyer** [comment]
Just to be clear: there is no need to rebase this one (I already applied all the changes we need from it). If you're doing it as an exercise then you should be able to  just"git fetch; git rebase origin/master", unless there are conflicts (which will show up in the terminal).

**Comment by oleersoy** [comment]
Well right now is saying that the fix referencing the 'codes' has not been fixed in master.  Did you fix this?  This is a link to the PR [codes](https://github.com/spring-guides/tut-spring-security-and-angular-js/pull/125/commits/a6bc642864de93ca1debfe197df3ce30470d9540)

**Comment by dsyer** [comment]
Here's the basic/README.adoc on master: https://github.com/spring-guides/tut-spring-security-and-angular-js/blob/master/basic/README.adoc. Looks like it was fixed to me? Maybe I'm reading the wrong section. What did you mean by "is saying"? What is saying that?

**Comment by oleersoy** [comment]
Oooops - you are right.  It is applied.  I was following the second path in these instructions [Updating a forked repository](http://stackoverflow.com/questions/7244321/how-do-i-update-a-github-forked-repository) and it made me when I was comparing the changes I thought we had missed it.  I'll give it another try - thanks!

**Pull request closed without merging**
